import type { LabId } from './lab';

/**
 * P(some frontier lab ships a text model within h hours), from per-lab market reads. Pure.
 *
 * The event is the one the calibration study scored (scripts/backtest/replay.ts,
 * data/backtest/v3-replay.json): a frontier lab (FRONTIER_LABS) has a text-output OpenRouter release
 * event (`releaseEvents`) whose first listing falls in (now, now + h]. Markets price named
 * releases; most launches are not named in advance, so the forecast is a noisy-OR of every lab's
 * market read and an "unpriced release" term fitted on history:
 *
 *   p = 1 − (1 − u(h)) · Π_lab (1 − p_lab),  then optionally σ(a + b · logit(p)).
 *
 * The study's verdict is in `FORECAST_CONSTANTS.recommendation`. It came back `lead-score`: at 72h no
 * formula beat the train-window base rate out of sample, so `p` is context for the page (base-rate
 * line, /backtest), not the DROPCON headline.
 */

/** Fitted values for one horizon, and how the shipped formula scored on the held-out window. */
export interface HorizonConstants {
  horizonHours: number;
  /** u: P(a frontier release no market prices) within the horizon, fitted by maximum likelihood on train. */
  unpriced: number;
  /** Logistic recalibration p' = σ(a + b·logit(p)); `{ a: 0, b: 1 }` is the identity. */
  calibration: { a: number; b: number };
  /** Share of train-window hours in which a frontier release landed within the horizon: formula (a). */
  baseRate: number;
  /** The shipped formula on the test window. Skill is Brier skill vs `baseRate`; the interval is a block bootstrap. */
  test: {
    hours: number;
    rate: number;
    brier: number;
    skill: number;
    skillCi95: [number, number];
    /** Calibration in the large within 0.05 and every bin of ≥100 hours within 0.20. */
    sane: boolean;
  };
}

export interface ForecastConstants {
  version: number;
  /** (d) noisy-OR, or (e) noisy-OR plus logistic recalibration: the better of the two at 72h out of sample. */
  formula: 'noisy-or' | 'noisy-or-cal';
  /** What the study decided for the DROPCON v3 headline. */
  recommendation: 'probability' | 'lead-score';
  /** Train window and the distinct release events in it. */
  fittedOn: { from: string; to: string; events: number };
  /** Held-out window and the distinct release events in it: the effective sample size. */
  testedOn: { from: string; to: string; events: number };
  /** One entry per fitted horizon (24h, 72h, 7d), ascending. */
  horizons: readonly HorizonConstants[];
}

/**
 * Generated by `pnpm backtest:replay` (data/backtest/v3-replay.json `constants`);
 * test/scripts/replay.test.ts fails if the two drift apart.
 */
export const FORECAST_CONSTANTS: ForecastConstants = {
  version: 1,
  formula: 'noisy-or',
  recommendation: 'lead-score',
  fittedOn: { from: '2026-04-01T00:00:00Z', to: '2026-07-16T19:00:00Z', events: 20 },
  testedOn: { from: '2026-07-16T19:00:00Z', to: '2026-09-26T00:00:00Z', events: 25 },
  horizons: [
    {
      horizonHours: 24,
      unpriced: 0.0891,
      calibration: { a: 0, b: 1 },
      baseRate: 0.1654,
      test: {
        hours: 1686,
        rate: 0.283,
        brier: 0.2097,
        skill: 0.032,
        skillCi95: [-0.246, 0.233],
        sane: false,
      },
    },
    {
      horizonHours: 72,
      unpriced: 0.234,
      calibration: { a: 0, b: 1 },
      baseRate: 0.3904,
      test: {
        hours: 1638,
        rate: 0.631,
        brier: 0.2913,
        skill: -0.002,
        skillCi95: [-0.566, 0.344],
        sane: false,
      },
    },
    {
      horizonHours: 168,
      unpriced: 0.5008,
      calibration: { a: 0, b: 1 },
      baseRate: 0.7316,
      test: { hours: 1542, rate: 0.94, brier: 0.0946, skill: 0.054, skillCi95: [-0.358, 0.665], sane: false },
    },
  ],
};

export interface ProbabilityLevel {
  level: 1 | 2 | 3 | 4 | 5;
  /** Lowest 72h probability at this level. */
  min: number;
  label: string;
}

/**
 * Bands on the 72h probability, level 1 (highest) first. The edges are the train-window 30/60/85/95%
 * quantiles of the 72h forecast rounded to 0.05, capped at 0.95 (pre-registered in the replay).
 * On the held-out window the observed release rate did not rise with the level (data/backtest/
 * v3-replay.json `levels.test`), which is part of why the headline stays the lead score.
 */
export const PROBABILITY_LEVELS: readonly ProbabilityLevel[] = [
  { level: 1, min: 0.95, label: '≥95%' },
  { level: 2, min: 0.7, label: '70–95%' },
  { level: 3, min: 0.45, label: '45–70%' },
  { level: 4, min: 0.3, label: '30–45%' },
  { level: 5, min: 0, label: '<30%' },
];

/** Image, video, audio and voice generators are not language-model releases. */
const NON_TEXT_FAMILY =
  /\b(image|imagen|nano[ -]?banana|veo|sora|video|audio|music|lyria|voice|tts|speech|genie)\b/i;

/** A release market's title names a text-model family (the only kind the forecast reads). */
export function isTextReleaseFamily(title: string): boolean {
  return !NON_TEXT_FAMILY.test(title);
}

export interface LabRead {
  labId: LabId;
  /** P(this lab releases within the horizon), e.g. its best text family's curve read at now + h. */
  p: number;
}

export interface ReleaseForecast {
  /** P(some frontier lab releases a text model within the horizon). */
  p: number;
  /** The unpriced-release term u(h) that went into `p`. */
  unpriced: number;
  components: {
    /** Noisy-OR of the lab reads alone. */
    market: number;
    /** 1 − (1 − unpriced)(1 − market), before any recalibration. */
    combined: number;
    /** The horizon whose fitted constants were used. */
    fittedHorizonHours: number;
    /** Valid reads, highest first. */
    labs: LabRead[];
  };
}

const LOGIT_EPS = 1e-3;

function probability(value: number): number {
  return Number.isFinite(value) ? Math.min(1, Math.max(0, value)) : 0;
}

/** The fitted horizon closest to `hours` on a log scale. */
function nearestHorizon(horizons: readonly HorizonConstants[], hours: number): HorizonConstants {
  const distance = (h: HorizonConstants) => Math.abs(Math.log(h.horizonHours / hours));
  return horizons.reduce((best, h) => (distance(h) < distance(best) ? h : best));
}

/**
 * P(a frontier text release within `horizonHours`). Lab reads combine by noisy-OR: the cross-lab
 * clustering test found labs no more synchronised than a shuffled baseline. A horizon between the
 * fitted ones borrows the nearest fit and rescales its unpriced term at constant hazard.
 * Non-finite or out-of-range reads are clamped to [0, 1]; a non-positive horizon has nothing to forecast.
 */
export function anyReleaseProbability(
  perLab: readonly LabRead[],
  horizonHours: number,
  constants: ForecastConstants = FORECAST_CONSTANTS,
): ReleaseForecast {
  const labs = perLab
    .map((l) => ({ labId: l.labId, p: probability(l.p) }))
    .sort((a, b) => b.p - a.p || a.labId.localeCompare(b.labId));
  if (!(horizonHours > 0) || !constants.horizons.length) {
    return { p: 0, unpriced: 0, components: { market: 0, combined: 0, fittedHorizonHours: 0, labs } };
  }
  const fit = nearestHorizon(constants.horizons, horizonHours);
  const u = probability(fit.unpriced);
  const unpriced = horizonHours === fit.horizonHours ? u : 1 - (1 - u) ** (horizonHours / fit.horizonHours);
  const market = 1 - labs.reduce((survive, l) => survive * (1 - l.p), 1);
  const combined = 1 - (1 - unpriced) * (1 - market);
  const { a, b } = fit.calibration;
  const identity = a === 0 && b === 1;
  const clipped = Math.min(1 - LOGIT_EPS, Math.max(LOGIT_EPS, combined));
  const p = identity ? combined : 1 / (1 + Math.exp(-(a + b * Math.log(clipped / (1 - clipped)))));
  return {
    p,
    unpriced,
    components: { market, combined, fittedHorizonHours: fit.horizonHours, labs },
  };
}

/** The DROPCON level (1 = highest) for a 72h probability. */
export function levelFromProbability(
  p: number,
  levels: readonly ProbabilityLevel[] = PROBABILITY_LEVELS,
): ProbabilityLevel['level'] {
  const value = probability(p);
  return (levels.find((l) => value >= l.min) ?? levels[levels.length - 1]).level;
}

/** The forecast as the dashboard shows it: context for the base-rate line, never the level. */
export interface ForecastSummary {
  horizonHours: number;
  /** P(some frontier lab lists a text model within the horizon). */
  p: number;
  /** The unpriced-release term that went into `p`. */
  unpriced: number;
  /** Noisy-OR of the trusted lab reads alone. */
  market: number;
  /** The trusted per-lab reads that went in, highest first. */
  labs: LabRead[];
  /** Share of train-window hours with a frontier text release within the horizon. */
  baseRate: number;
  /** Out-of-sample Brier skill against `baseRate`, and its 95% block-bootstrap interval. */
  skill: number;
  skillCi95: [number, number];
  trainWindow: { from: string; to: string };
  recommendation: ForecastConstants['recommendation'];
  /** False when Polymarket was down: `p` is then the unpriced term alone. */
  oddsAvailable: boolean;
}

/** Summarise `anyReleaseProbability` at `horizonHours` with the fit that backs it. */
export function forecastSummary(
  perLab: readonly LabRead[],
  oddsAvailable: boolean,
  horizonHours = 72,
  constants: ForecastConstants = FORECAST_CONSTANTS,
): ForecastSummary {
  const forecast = anyReleaseProbability(oddsAvailable ? perLab : [], horizonHours, constants);
  const fit = constants.horizons.length ? nearestHorizon(constants.horizons, horizonHours) : undefined;
  return {
    horizonHours,
    p: forecast.p,
    unpriced: forecast.unpriced,
    market: forecast.components.market,
    labs: forecast.components.labs,
    baseRate: fit?.baseRate ?? 0,
    skill: fit?.test.skill ?? 0,
    skillCi95: fit?.test.skillCi95 ?? [0, 0],
    trainWindow: { from: constants.fittedOn.from, to: constants.fittedOn.to },
    recommendation: constants.recommendation,
    oddsAvailable,
  };
}
