/**
 * The labelled tier review of the 45 in-window v3-replay releases (2026-04-01 to 2026-09-26): each
 * release's tier as a person read it, whether the call is ambiguous, and why. This is curated input,
 * not generated: `labels.ts` reproduces every tier here from the rules in the lab registry plus
 * `TIER_OVERRIDES`, and `test/scripts/labels.test.ts` fails when they disagree. Edit it only to
 * record a new review decision, and then change the rules or overrides to match.
 */
import type { LabId, Tier } from '../../src/domain/lab';

export interface TierReview {
  /** The marker's first OpenRouter listing, as v3-replay.json prints it. */
  at: string;
  labId: LabId;
  /** The reviewed skus, `[F]`/`[M]` marking each model's own tier where they differ. */
  models: string;
  tier: Tier;
  /** A reasonable reader could tier it the other way. */
  ambiguous: boolean;
  /** The rule or override the review cites. */
  ruleOrOverride: string;
  note?: string;
}

export const TIER_REVIEW: readonly TierReview[] = [
  {
    at: '2026-04-02T12:39:17Z',
    labId: 'qwen',
    models: 'qwen3.6-plus',
    tier: 'flagship',
    ambiguous: true,
    ruleOrOverride: 'qwen (b): debut of a new version',
    note: "A Plus-tier model, flagship only through the debut rule. The guidance's 'Qwen major/Max' would make it minor (scenario S4). The qwen.ai blog was on HN at 06:17Z, 6h before the OpenRouter listing.",
  },
  {
    at: '2026-04-02T16:48:06Z',
    labId: 'google',
    models: 'gemma-4-31b-it',
    tier: 'minor',
    ambiguous: false,
    ruleOrOverride: 'google: gemma',
    note: 'An open small model, even though Gemma 4 got its own launch blog.',
  },
  {
    at: '2026-04-03T14:53:09Z',
    labId: 'google',
    models: 'gemma-4-26b-a4b-it',
    tier: 'minor',
    ambiguous: false,
    ruleOrOverride: 'google: gemma',
  },
  {
    at: '2026-04-16T14:51:40Z',
    labId: 'anthropic',
    models: 'claude-opus-4.7',
    tier: 'flagship',
    ambiguous: false,
    ruleOrOverride: 'anthropic: opus new version',
  },
  {
    at: '2026-04-24T03:17:46Z',
    labId: 'deepseek',
    models: 'deepseek-v4-flash, deepseek-v4-pro',
    tier: 'flagship',
    ambiguous: false,
    ruleOrOverride: 'deepseek: new V version, pro',
    note: 'The Pro member makes the event flagship; Flash alone would be minor.',
  },
  {
    at: '2026-04-24T17:31:33Z',
    labId: 'openai',
    models: 'gpt-5.5, gpt-5.5-pro',
    tier: 'flagship',
    ambiguous: false,
    ruleOrOverride: 'openai: new gpt-N.M',
    note: 'Timing: announced 04-23T18:01Z; OpenRouter listed it 23.5h later, and a Codex build exposed it 38h early. If ChatGPT access came with the announcement, first availability is about a day earlier.',
  },
  {
    at: '2026-04-27T01:57:44Z',
    labId: 'qwen',
    models: 'qwen3.6-max-preview (+27b, 35b-a3b, flash, 3.5-plus-20260420)',
    tier: 'flagship',
    ambiguous: false,
    ruleOrOverride: 'qwen (a): first Max of a version',
    note: 'A preview of a version not yet shipped is still first availability. The flagship member listed at 03:24Z. The qwen.ai blog was on HN at 04-20T14:05Z, 6.5 days before the OpenRouter listing.',
  },
  {
    at: '2026-04-30T23:30:21Z',
    labId: 'xai',
    models: 'grok-4.3',
    tier: 'flagship',
    ambiguous: false,
    ruleOrOverride: 'xai: grok-N.M',
    note: "Timing: HN reported a Grok 4.3 beta on grok.com on 04-17 (HN 47808588) and on 04-21 (grok.com/release-notes), 13 days before OpenRouter. Under 'a limited preview counts', availability is probably Apr 17.",
  },
  {
    at: '2026-05-05T16:56:52Z',
    labId: 'openai',
    models: 'gpt-chat-latest',
    tier: 'minor',
    ambiguous: false,
    ruleOrOverride: 'alias (-latest)',
    note: 'OpenRouter: the API alias chat-latest, which points at the current ChatGPT Instant model.',
  },
  {
    at: '2026-05-07T15:47:08Z',
    labId: 'google',
    models: 'gemini-3.1-flash-lite',
    tier: 'minor',
    ambiguous: false,
    ruleOrOverride: 'google: flash-lite',
    note: 'The GA of the 2026-03-03 preview.',
  },
  {
    at: '2026-05-19T12:30:00Z',
    labId: 'google',
    models: 'gemini-3.5-flash',
    tier: 'flagship',
    ambiguous: true,
    ruleOrOverride: 'google: first model of the N.5 generation',
    note: 'A Flash-tier model, the headline launch at the I/O keynote, and it settled the Gemini 3.5 and 3.2 markets. Without it Google has no flagship in the window (S1).',
  },
  {
    at: '2026-05-20T17:28:43Z',
    labId: 'xai',
    models: 'grok-build-0.1',
    tier: 'minor',
    ambiguous: true,
    ruleOrOverride: 'xai: build',
    note: "A new family name, which the guidance counts as flagship. But OpenRouter calls it a 'fast coding model', the analogue of Codex, and its $1 / $2 pricing is below Grok 4.3.",
  },
  {
    at: '2026-05-21T15:21:01Z',
    labId: 'qwen',
    models: 'qwen3.7-max',
    tier: 'flagship',
    ambiguous: false,
    ruleOrOverride: 'qwen (a)+(b)',
    note: 'Timing: the qwen.ai blog was on HN at 05-20T10:35Z, 29h before OpenRouter.',
  },
  {
    at: '2026-05-27T18:04:51Z',
    labId: 'anthropic',
    models: 'claude-opus-4.8',
    tier: 'flagship',
    ambiguous: false,
    ruleOrOverride: 'anthropic: opus new version',
    note: 'OpenRouter listed it 22.7h before the announcement.',
  },
  {
    at: '2026-06-03T13:03:03Z',
    labId: 'qwen',
    models: 'qwen3.7-plus',
    tier: 'minor',
    ambiguous: false,
    ruleOrOverride: 'qwen: plus after debut',
    note: "A Polymarket 'Next Qwen Plus' market exists, but Plus after Max is a mid tier.",
  },
  {
    at: '2026-06-09T12:18:35Z',
    labId: 'anthropic',
    models: 'claude-fable-5',
    tier: 'flagship',
    ambiguous: false,
    ruleOrOverride: 'anthropic: new family above Opus (Fable/Mythos)',
  },
  {
    at: '2026-06-30T18:11:23Z',
    labId: 'anthropic',
    models: 'claude-sonnet-5',
    tier: 'flagship',
    ambiguous: false,
    ruleOrOverride: 'anthropic: sonnet new version',
    note: 'Timing: announced 15:01Z, 3h before OpenRouter.',
  },
  {
    at: '2026-07-08T15:05:54Z',
    labId: 'xai',
    models: 'grok-4.5',
    tier: 'flagship',
    ambiguous: false,
    ruleOrOverride: 'xai: grok-N.M',
  },
  {
    at: '2026-07-09T09:54:10Z',
    labId: 'openai',
    models: 'gpt-5.6-sol/-terra (+pro), gpt-5.6-luna (+pro)',
    tier: 'flagship',
    ambiguous: false,
    ruleOrOverride: 'openai: new gpt-N.M sol/terra',
    note: 'The Luna members alone would be minor.',
  },
  {
    at: '2026-07-16T15:29:01Z',
    labId: 'meta',
    models: 'muse-spark-1.1',
    tier: 'flagship',
    ambiguous: true,
    ruleOrOverride: 'meta: muse-spark N.M',
    note: "A point version of Meta's main line, treated like Grok 4.x. The guidance's 'Muse majors' would make it minor (S3). Timing: Meta launched its model API on 07-09 (HN 48846184, ai.meta.com blog), 7 days before OpenRouter. Muse Spark 1.0 (meta.ai, 04-08) is missing from the 45.",
  },
  {
    at: '2026-07-21T15:12:06Z',
    labId: 'google',
    models: 'gemini-3.6-flash, gemini-3.5-flash-lite',
    tier: 'minor',
    ambiguous: true,
    ruleOrOverride: 'google: flash point bump',
    note: '3.6 opens a new Gemini version number but not an N.0/N.5 generation. Google now bumps Flash monthly while Pro is delayed (S2).',
  },
  {
    at: '2026-07-24T17:02:24Z',
    labId: 'anthropic',
    models: 'claude-opus-5',
    tier: 'flagship',
    ambiguous: false,
    ruleOrOverride: 'anthropic: opus new version',
  },
  {
    at: '2026-07-27T22:16:01Z',
    labId: 'qwen',
    models: 'qwen3.7-flash',
    tier: 'minor',
    ambiguous: false,
    ruleOrOverride: 'qwen: flash',
  },
  {
    at: '2026-07-31T06:21:48Z',
    labId: 'deepseek',
    models: 'deepseek-v4-flash-0731',
    tier: 'minor',
    ambiguous: false,
    ruleOrOverride: 'deepseek: dated refresh',
    note: 'A re-post-trained revision of V4 Flash.',
  },
  {
    at: '2026-08-05T19:48:07Z',
    labId: 'meta',
    models: 'muse-spark-1.2',
    tier: 'flagship',
    ambiguous: true,
    ruleOrOverride: 'meta: muse-spark N.M',
    note: 'Same question as 1.1 (S3). HN launch story at 19:15Z, launched alongside Muse Code.',
  },
  {
    at: '2026-08-09T19:06:34Z',
    labId: 'meta',
    models: 'muse-glimmer-30b',
    tier: 'minor',
    ambiguous: false,
    ruleOrOverride: 'meta: glimmer (small open distill)',
    note: 'A new family name, but a 30B open-weight model distilled from Spark, the Meta analogue of Gemma.',
  },
  {
    at: '2026-08-12T15:35:57Z',
    labId: 'xai',
    models: 'grok-4.6',
    tier: 'flagship',
    ambiguous: false,
    ruleOrOverride: 'xai: grok-N.M',
  },
  {
    at: '2026-08-12T15:42:44Z',
    labId: 'deepseek',
    models: 'deepseek-v4-pro-0813',
    tier: 'minor',
    ambiguous: true,
    ruleOrOverride: 'deepseek: dated refresh',
    note: "OpenRouter: 'the GA release of DeepSeek V4 Pro'. Dated DeepSeek refreshes (V3-0324, R1-0528) have drawn flagship-level attention before.",
  },
  {
    at: '2026-08-12T16:21:42Z',
    labId: 'qwen',
    models: 'qwen3.8-2.4t-a95b',
    tier: 'flagship',
    ambiguous: true,
    ruleOrOverride: 'qwen (b): debut, 2.4T open weights',
    note: 'A size-named slug, but it is the open-weight Qwen3.8 Max. Timing is badly off: the Qwen 3.8 / 3.8 Max Preview was on HN at 07-19T08:44Z, and Max GA was 08-03, so OpenRouter lags first availability by 24 days.',
  },
  {
    at: '2026-08-13T17:03:01Z',
    labId: 'google',
    models: 'gemini-3.7-flash',
    tier: 'minor',
    ambiguous: true,
    ruleOrOverride: 'google: flash point bump',
    note: 'S2.',
  },
  {
    at: '2026-08-14T15:55:10Z',
    labId: 'qwen',
    models: 'qwen3.8-27b',
    tier: 'minor',
    ambiguous: false,
    ruleOrOverride: 'qwen: open size after debut',
  },
  {
    at: '2026-08-21T11:26:03Z',
    labId: 'deepseek',
    models: 'deepseek-v4-flash-vision-exp',
    tier: 'minor',
    ambiguous: false,
    ruleOrOverride: 'deepseek: exp/vision',
  },
  {
    at: '2026-08-21T18:21:16Z',
    labId: 'meta',
    models: 'muse-spark-1.2-contributor',
    tier: 'minor',
    ambiguous: false,
    ruleOrOverride: 'meta: contributor tier',
    note: 'A cheaper tier ($0.10 / $0.20) of an already-shipped 1.2.',
  },
  {
    at: '2026-08-26T19:37:40Z',
    labId: 'qwen',
    models: 'qwen3.8-flash',
    tier: 'minor',
    ambiguous: false,
    ruleOrOverride: 'qwen: flash',
    note: 'Announced 25h ahead as Qwen3.8-Flash-Next.',
  },
  {
    at: '2026-09-01T18:03:58Z',
    labId: 'anthropic',
    models: 'claude-fable-5.1',
    tier: 'flagship',
    ambiguous: false,
    ruleOrOverride: 'anthropic: fable new version',
  },
  {
    at: '2026-09-02T15:14:16Z',
    labId: 'google',
    models: 'gemini-3.8-flash',
    tier: 'minor',
    ambiguous: true,
    ruleOrOverride: 'google: flash point bump',
    note: "OpenRouter: 'Google's most intelligent Flash model'. A WSJ scoop came 16h before, and a Flash 3.8+ market exists (S2).",
  },
  {
    at: '2026-09-02T19:45:59Z',
    labId: 'meta',
    models: 'muse-spark-1.3, muse-spark-1.3-contributor',
    tier: 'flagship',
    ambiguous: true,
    ruleOrOverride: 'meta: muse-spark N.M',
    note: "S3. It settled the 'Next Meta Muse Spark (1.3+)' market.",
  },
  {
    at: '2026-09-03T21:08:24Z',
    labId: 'qwen',
    models: 'qwen3.8-max-0902',
    tier: 'minor',
    ambiguous: true,
    ruleOrOverride: 'OVERRIDE -> minor',
    note: 'A snapshot of an already-shipped Max. Without the override, rule (a) would call it flagship.',
  },
  {
    at: '2026-09-04T20:13:55Z',
    labId: 'openai',
    models: 'gpt-6-astra, gpt-6-astra-pro',
    tier: 'flagship',
    ambiguous: false,
    ruleOrOverride: 'openai: new gpt-N astra',
    note: 'Announced 09-03, generally available 09-04. The availability event is the 04th, not the announcement.',
  },
  {
    at: '2026-09-10T06:21:25Z',
    labId: 'deepseek',
    models: 'deepseek-v4.1-flash',
    tier: 'minor',
    ambiguous: true,
    ruleOrOverride: 'deepseek: flash-only version',
    note: "A new mid version and a new architecture (CED), but only in the Flash tier. It settled the 'Next DeepSeek Flash' market. A V4.1 Pro would be flagship.",
  },
  {
    at: '2026-09-21T03:05:54Z',
    labId: 'qwen',
    models: 'qwen3.8-omni-flash',
    tier: 'minor',
    ambiguous: false,
    ruleOrOverride: 'qwen: omni/flash',
  },
  {
    at: '2026-09-21T16:19:01Z',
    labId: 'xai',
    models: 'grok-4.7',
    tier: 'flagship',
    ambiguous: false,
    ruleOrOverride: 'xai: grok-N.M',
    note: 'Announced 15:50Z.',
  },
  {
    at: '2026-09-22T16:32:12Z',
    labId: 'anthropic',
    models: 'claude-opus-5.5',
    tier: 'flagship',
    ambiguous: false,
    ruleOrOverride: 'anthropic: opus new version',
  },
  {
    at: '2026-09-22T18:12:55Z',
    labId: 'openai',
    models: 'gpt-6-sol (+pro), gpt-6-luna (+pro)',
    tier: 'flagship',
    ambiguous: true,
    ruleOrOverride: 'openai: new gpt-N sol',
    note: "OpenRouter places Sol below the flagship Astra, which shipped 18 days earlier. Labelled flagship by analogy with Sonnet; the whole-window rate doesn't move either way (S5).",
  },
  {
    at: '2026-09-23T19:20:28Z',
    labId: 'qwen',
    models: 'qwen3.8-max-prime',
    tier: 'minor',
    ambiguous: true,
    ruleOrOverride: 'qwen: max SKU variant (pin as override)',
    note: 'A higher-priced, higher-throughput SKU of the already-shipped 3.8 Max. It could be read as a new top tier.',
  },
];
